version: '3.7'
services:
  app:
    image: lidofinance/validator-ejector@sha256:e5768026ddec080faa6d0ff27d3b043bc874855fbbd38d4f9789bea14dcf8592
    container_name: validator-ejector
    restart: unless-stopped
    environment:
      - EXECUTION_NODE=${EXECUTION_NODE}
      - CONSENSUS_NODE=${CONSENSUS_NODE}
      - LOCATOR_ADDRESS=${LOCATOR_ADDRESS}
      - STAKING_MODULE_ID=${STAKING_MODULE_ID}
      - OPERATOR_ID=${OPERATOR_ID}
      - MESSAGES_LOCATION=${MESSAGES_LOCATION}
      - MESSAGES_PASSWORD=${MESSAGES_PASSWORD}
      - MESSAGES_PASSWORD_FILE=${MESSAGES_PASSWORD_FILE}
      - ORACLE_ADDRESSES_ALLOWLIST=${ORACLE_ADDRESSES_ALLOWLIST}
      - BLOCKS_PRELOAD=${BLOCKS_PRELOAD}
      - BLOCKS_LOOP=${BLOCKS_LOOP}
      - JOB_INTERVAL=${JOB_INTERVAL}
      - HTTP_PORT=${HTTP_PORT}
      - RUN_METRICS=${RUN_METRICS}
      - RUN_HEALTH_CHECK=${RUN_HEALTH_CHECK}
      - LOGGER_LEVEL=${LOGGER_LEVEL}
      - LOGGER_FORMAT=${LOGGER_FORMAT}
      - LOGGER_SECRETS=${LOGGER_SECRETS}
      - LOGGER_SECRETS_FILE=${LOGGER_SECRETS_FILE}
      - DRY_RUN=${DRY_RUN}
    ports:
      - '${HTTP_PORT}:${HTTP_PORT}'
    volumes:
      - ./messages:/app/messages
