{
 "title": "Validator Ejector",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Exit Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Valid Exit Messages",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "validator_ejector_exit_messages{valid=\"true\"}"
    }
   ]
  },
  {
   "title": "Invalid Exit Messages",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "validator_ejector_exit_messages{valid=\"false\"}"
    }
   ]
  },
  {
   "title": "Exit Messages Left",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(validator_ejector_exit_messages{valid=\"true\"} - on () validator_ejector_exit_actions{result=\"success\"}) / on () (validator_ejector_exit_messages{valid=\"true\"} > 0 or on() vector(1)) * 100"
    }
   ]
  },
  {
   "title": "Exit Messages Left",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "validator_ejector_exit_messages{valid=\"true\"} - on () validator_ejector_exit_actions{result=\"success\"}"
    }
   ]
  },
  {
   "title": "Exit Actions Success",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(validator_ejector_exit_actions{result=\"success\"})"
    }
   ]
  },
  {
   "title": "Exit Action Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(validator_ejector_exit_actions{result=\"error\"})"
    }
   ]
  },
  { "title": "Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Successful Jobs Since Start",
   "type": "stat",
   "description": "It's currently not possible to calculate values in selected range with perfect accuracy.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "validator_ejector_job_duration_seconds_count{result=\"success\"}"
    }
   ]
  },
  {
   "title": "Job Errors Since Start",
   "type": "stat",
   "description": "It's currently not possible to calculate values in selected range with perfect accuracy.",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "validator_ejector_job_duration_seconds_count{result=\"error\"}"
    }
   ]
  },
  {
   "title": "Jobs Duration",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(validator_ejector_job_duration_seconds_bucket [1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Job Time Interval",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "validator_ejector_job_duration_seconds_bucket{le=\"+Inf\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Node Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Execution Node Request Duration",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(rate(validator_ejector_execution_request_duration_seconds_bucket [1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Execution Node Request Average Duration",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(validator_ejector_execution_request_duration_seconds_sum)/sum(validator_ejector_execution_request_duration_seconds_count)"
    }
   ]
  },
  {
   "title": "Consensus Node Request Average Duration",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(validator_ejector_consensus_request_duration_seconds_sum)/sum(validator_ejector_consensus_request_duration_seconds_count)"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "{container_name=\"validator-ejector\"}"
    }
   ]
  }
 ]
}